kind: pipeline
type: exec
name: Build all hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: Show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata
- name: Run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace
- name: Build kartoffel
  commands:
  - nix build '.#nixosConfigurations.kartoffel.config.system.build.toplevel'
- name: Build ahorn
  commands:
  - nix build '.#nixosConfigurations.ahorn.config.system.build.toplevel'
- name: Build porree
  commands:
  - nix build '.#nixosConfigurations.porree.config.system.build.toplevel'
- name: Build kfbox
  commands:
  - nix build '.#nixosConfigurations.kfbox.config.system.build.toplevel'
- name: Build bob
  commands:
  - nix build '.#nixosConfigurations.bob.config.system.build.toplevel'
# - name: Build birne
#   commands:
#   - nix build '.#nixosConfigurations.birne.config.system.build.toplevel' --out-link ./result-birne

---
kind: pipeline
name: Notifications
type: docker

platform:
  os: linux
  arch: amd64

steps:
# http://plugins.drone.io/appleboy/drone-discord/
- name: Notify IRC
  image: plugins/irc
  settings:
    nick: drone-bot
    channel: "#lounge-rocks"
    host: chat.freenode.net
    port: 6667
    template: "[{{build.status}}]: {{build.message}} | #{{truncate build.commit 8}} {{build.event}} on {{repo.owner}}/{{repo.name}}/{{build.branch}} by {{build.author}} - {{build.link}}"

trigger:
  branch:
  - main
  event:
  - pull_request
  - push

---
kind: pipeline
type: docker
name: Update Flakes

steps:
- name: Update flake.lock
  image: nixpkgs/nix-flakes
  commands:
  - nix flake update
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable

- name: Push updated flake.lock
  image: appleboy/drone-git-push
  settings:
    branch: update-flake
    remote: git@github.com:pinpox/nixos.git
    force: true
    commit: true
    force: true
    commit_message: "❄️ Update flake.lock"
    ssh_key:
      from_secret: deploy_key

- name: Notify IRC
  image: plugins/irc
  settings:
    nick: drone-bot
    channel: "#lounge-rocks"
    host: chat.freenode.net
    port: 6667
    template: "[{{build.status}}]: {{build.message}} | #{{truncate build.commit 8}} {{build.event}} on {{repo.owner}}/{{repo.name}}/{{build.branch}} by {{build.author}} - {{build.link}}"

trigger:
  event:
  - cron
  cron:
  - daily

# - name: Notify IRC
#   image: plugins/irc
#   settings:
#     nick: drone-bot
#     channel: "#lounge-rocks"
#     host: chat.freenode.net
#     port: 6667
#     template: "[{{build.status}}]: {{build.message}} | #{{truncate build.commit 8}} {{build.event}} on {{repo.owner}}/{{repo.name}}/{{build.branch}} by {{build.author}} - {{build.link}}"

# trigger:
#   branch:
#   - main

