---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  commands:
  - pwd
  - ls
  - nix-build krops.nix -A all
  - whoami
  - nix shell 'nixpkgs#hello' -c hello
  - echo "hello world"
