labels:
  backend: local
  platform: linux/amd64

when:
  - event: [push, manual]

steps:
  - name: setup-attic
    image: bash
    environment:
      ATTIC_KEY:
        from_secret: attic_key
    commands:
      - attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default

  - name: build-birne
    image: bash
    commands:
      - nix build '.#nixosConfigurations.birne.config.system.build.toplevel' -o 'result-birne'

  - name: push-birne
    image: bash
    environment:
      ATTIC_KEY:
        from_secret: attic_key
    commands:
      - attic push lounge-rocks:nix-cache 'result-birne'

  - name: build-kartoffel
    image: bash
    commands:
      - nix build '.#nixosConfigurations.kartoffel.config.system.build.toplevel' -o 'result-kartoffel'

  - name: push-kartoffel
    image: bash
    environment:
      ATTIC_KEY:
        from_secret: attic_key
    commands:
      - attic push lounge-rocks:nix-cache 'result-kartoffel'

  - name: build-kfbox
    image: bash
    commands:
      - nix build '.#nixosConfigurations.kfbox.config.system.build.toplevel' -o 'result-kfbox'

  - name: push-kfbox
    image: bash
    environment:
      ATTIC_KEY:
        from_secret: attic_key
    commands:
      - attic push lounge-rocks:nix-cache 'result-kfbox'

  - name: build-kiwi
    image: bash
    commands:
      - nix build '.#nixosConfigurations.kiwi.config.system.build.toplevel' -o 'result-kiwi'

  - name: push-kiwi
    image: bash
    environment:
      ATTIC_KEY:
        from_secret: attic_key
    commands:
      - attic push lounge-rocks:nix-cache 'result-kiwi'

  - name: build-tanne
    image: bash
    commands:
      - nix build '.#nixosConfigurations.tanne.config.system.build.toplevel' -o 'result-tanne'

  - name: push-tanne
    image: bash
    environment:
      ATTIC_KEY:
        from_secret: attic_key
    commands:
      - attic push lounge-rocks:nix-cache 'result-tanne'

  - name: build-limette
    image: bash
    commands:
      - nix build '.#nixosConfigurations.limette.config.system.build.toplevel' -o 'result-limette'

  - name: push-limette
    image: bash
    environment:
      ATTIC_KEY:
        from_secret: attic_key
    commands:
      - attic push lounge-rocks:nix-cache 'result-limette'

  - name: build-porree
    image: bash
    commands:
      - nix build '.#nixosConfigurations.porree.config.system.build.toplevel' -o 'result-porree'

  - name: push-porree
    image: bash
    environment:
      ATTIC_KEY:
        from_secret: attic_key
    commands:
      - attic push lounge-rocks:nix-cache 'result-porree'
