{ config, ... }:
with config.pinpox.colors;
{
  "*.default" = true;
  "*error.bold" = true;
  "statusline*.default" = true;
  "border.bg" = "#${Black}";
  "border.fg" = "#${Blue}";
  "completion_pill.reverse" = true;
  "default.bg" = "#${Black}";
  "dirlist_default.selected.bg" = "#${BrightBlack}";
  "dirlist_default.selected.fg" = "#${White}";
  "dirlist_recent.selected.bg" = "#${White}";
  "dirlist_recent.selected.fg" = "#${BrightBlack}";
  "dirlist_unread.fg" = "#${BrightGreen}";
  "dirlist_unread.selected.bg" = "#${BrightBlack}";
  "dirlist_unread.selected.fg" = "#${BrightGreen}";
  "error.fg" = "#${BrightRed}";
  "header.bold" = true;
  "header.fg" = "#${BrightBlue}";
  "msglist_default.selected.bg" = "#${White}";
  "msglist_default.selected.fg" = "#${BrightBlack}";
  "msglist_deleted.fg" = "#${BrightRed}";
  "msglist_deleted.selected.reverse" = "toggle";
  "msglist_marked.fg" = "#${BrightYellow}";
  "msglist_marked.selected.bg" = "#${BrightBlack}";
  "msglist_marked.selected.fg" = "#${BrightYellow}";
  "msglist_read.selected.bg" = "#${BrightBlack}";
  "msglist_read.selected.fg" = "#${White}";
  "msglist_result.fg" = "#${BrightYellow}";
  "msglist_result.selected.bg" = "#${BrightBlack}";
  "msglist_unread.bold" = true;
  "msglist_unread.fg" = "#${BrightGreen}";
  "msglist_unread.selected.bg" = "#${BrightBlack}";
  "selector_chooser.bold" = true;
  "selector_focused.reverse" = true;
  "statusline_default.bg" = "#${Magenta}";
  "statusline_default.fg" = "#${BrightWhite}";
  "statusline_error.fg" = "#${BrightRed}";
  "statusline_error.reverse" = true;
  "success.fg" = "#${BrightGreen}";
  "tab.bg" = "#${Blue}";
  "tab.fg" = "#${White}";
  "tab.selected.bg" = "#${BrightWhite}";
  "tab.selected.fg" = "#${Blue}";
  "title.reverse" = true;
  "warning.fg" = "#${BrightYellow}";
}
