#!/usr/bin/env bash

ZJ_SESSIONS=$(zellij list-sessions -n)
NO_SESSIONS=$(echo "${ZJ_SESSIONS}" | wc -l)

if [ "${NO_SESSIONS}" -ge 2 ]; then
    zellij attach "$(echo "${ZJ_SESSIONS}" | fzf | cut -d' ' -f1)"
else
   zellij attach -c
fi
